/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "GBM",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.GBM__factory>;
    getContractFactory(
      name: "GBMInitiator",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.GBMInitiator__factory>;
    getContractFactory(
      name: "IGBM",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IGBM__factory>;
    getContractFactory(
      name: "IGBMInitiator",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IGBMInitiator__factory>;
    getContractFactory(
      name: "MassRegistrer",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MassRegistrer__factory>;
    getContractFactory(
      name: "Migrations",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Migrations__factory>;
    getContractFactory(
      name: "ERC1155Generic",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC1155Generic__factory>;
    getContractFactory(
      name: "ERC20Generic",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC20Generic__factory>;
    getContractFactory(
      name: "ERC721Generic",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC721Generic__factory>;
    getContractFactory(
      name: "IERC1155",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1155__factory>;
    getContractFactory(
      name: "IERC1155TokenReceiver",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1155TokenReceiver__factory>;
    getContractFactory(
      name: "IERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC165__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "IERC721",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721__factory>;
    getContractFactory(
      name: "IERC721TokenReceiver",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721TokenReceiver__factory>;
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;

    getContractAt(
      name: "GBM",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.GBM>;
    getContractAt(
      name: "GBMInitiator",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.GBMInitiator>;
    getContractAt(
      name: "IGBM",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IGBM>;
    getContractAt(
      name: "IGBMInitiator",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IGBMInitiator>;
    getContractAt(
      name: "MassRegistrer",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.MassRegistrer>;
    getContractAt(
      name: "Migrations",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Migrations>;
    getContractAt(
      name: "ERC1155Generic",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC1155Generic>;
    getContractAt(
      name: "ERC20Generic",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC20Generic>;
    getContractAt(
      name: "ERC721Generic",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC721Generic>;
    getContractAt(
      name: "IERC1155",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC1155>;
    getContractAt(
      name: "IERC1155TokenReceiver",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC1155TokenReceiver>;
    getContractAt(
      name: "IERC165",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC165>;
    getContractAt(
      name: "IERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "IERC721",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721>;
    getContractAt(
      name: "IERC721TokenReceiver",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721TokenReceiver>;
    getContractAt(
      name: "Ownable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
