/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC1155Generic } from "./ERC1155Generic";
export type { ERC20Generic } from "./ERC20Generic";
export type { ERC721Generic } from "./ERC721Generic";
export type { IERC1155 } from "./IERC1155";
export type { IERC1155TokenReceiver } from "./IERC1155TokenReceiver";
export type { IERC165 } from "./IERC165";
export type { IERC20 } from "./IERC20";
export type { IERC721 } from "./IERC721";
export type { IERC721TokenReceiver } from "./IERC721TokenReceiver";
export type { Ownable } from "./Ownable";
