/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { GBM } from "./GBM";
export type { GBMInitiator } from "./GBMInitiator";
export type { IGBM } from "./IGBM";
export type { IGBMInitiator } from "./IGBMInitiator";
