/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface MassRegistrerInterface extends utils.Interface {
  functions: {
    "massRegistrerERC1155Default(address,address,address,uint256,uint256,uint256)": FunctionFragment;
    "massRegistrerERC1155Each(address,address,address,uint256,uint256,uint256)": FunctionFragment;
    "massRegistrerERC721Default(address,address,address,uint256,uint256)": FunctionFragment;
    "massRegistrerERC721Each(address,address,address,uint256,uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "massRegistrerERC1155Default"
      | "massRegistrerERC1155Each"
      | "massRegistrerERC721Default"
      | "massRegistrerERC721Each"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "massRegistrerERC1155Default",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "massRegistrerERC1155Each",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "massRegistrerERC721Default",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "massRegistrerERC721Each",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "massRegistrerERC1155Default",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "massRegistrerERC1155Each",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "massRegistrerERC721Default",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "massRegistrerERC721Each",
    data: BytesLike
  ): Result;

  events: {};
}

export interface MassRegistrer extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: MassRegistrerInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    massRegistrerERC1155Default(
      _GBM: PromiseOrValue<string>,
      _initiator: PromiseOrValue<string>,
      _ERC1155Contract: PromiseOrValue<string>,
      _tokenID: PromiseOrValue<BigNumberish>,
      _indexStart: PromiseOrValue<BigNumberish>,
      _indexEnd: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    massRegistrerERC1155Each(
      _GBM: PromiseOrValue<string>,
      _initiator: PromiseOrValue<string>,
      _ERC1155Contract: PromiseOrValue<string>,
      _tokenID: PromiseOrValue<BigNumberish>,
      _indexStart: PromiseOrValue<BigNumberish>,
      _indexEnd: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    massRegistrerERC721Default(
      _GBM: PromiseOrValue<string>,
      _initiator: PromiseOrValue<string>,
      _ERC721Contract: PromiseOrValue<string>,
      _tokenIDStart: PromiseOrValue<BigNumberish>,
      _tokenIDEnd: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    massRegistrerERC721Each(
      _GBM: PromiseOrValue<string>,
      _initiator: PromiseOrValue<string>,
      _ERC721Contract: PromiseOrValue<string>,
      _tokenIDStart: PromiseOrValue<BigNumberish>,
      _tokenIDEnd: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  massRegistrerERC1155Default(
    _GBM: PromiseOrValue<string>,
    _initiator: PromiseOrValue<string>,
    _ERC1155Contract: PromiseOrValue<string>,
    _tokenID: PromiseOrValue<BigNumberish>,
    _indexStart: PromiseOrValue<BigNumberish>,
    _indexEnd: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  massRegistrerERC1155Each(
    _GBM: PromiseOrValue<string>,
    _initiator: PromiseOrValue<string>,
    _ERC1155Contract: PromiseOrValue<string>,
    _tokenID: PromiseOrValue<BigNumberish>,
    _indexStart: PromiseOrValue<BigNumberish>,
    _indexEnd: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  massRegistrerERC721Default(
    _GBM: PromiseOrValue<string>,
    _initiator: PromiseOrValue<string>,
    _ERC721Contract: PromiseOrValue<string>,
    _tokenIDStart: PromiseOrValue<BigNumberish>,
    _tokenIDEnd: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  massRegistrerERC721Each(
    _GBM: PromiseOrValue<string>,
    _initiator: PromiseOrValue<string>,
    _ERC721Contract: PromiseOrValue<string>,
    _tokenIDStart: PromiseOrValue<BigNumberish>,
    _tokenIDEnd: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    massRegistrerERC1155Default(
      _GBM: PromiseOrValue<string>,
      _initiator: PromiseOrValue<string>,
      _ERC1155Contract: PromiseOrValue<string>,
      _tokenID: PromiseOrValue<BigNumberish>,
      _indexStart: PromiseOrValue<BigNumberish>,
      _indexEnd: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    massRegistrerERC1155Each(
      _GBM: PromiseOrValue<string>,
      _initiator: PromiseOrValue<string>,
      _ERC1155Contract: PromiseOrValue<string>,
      _tokenID: PromiseOrValue<BigNumberish>,
      _indexStart: PromiseOrValue<BigNumberish>,
      _indexEnd: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    massRegistrerERC721Default(
      _GBM: PromiseOrValue<string>,
      _initiator: PromiseOrValue<string>,
      _ERC721Contract: PromiseOrValue<string>,
      _tokenIDStart: PromiseOrValue<BigNumberish>,
      _tokenIDEnd: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    massRegistrerERC721Each(
      _GBM: PromiseOrValue<string>,
      _initiator: PromiseOrValue<string>,
      _ERC721Contract: PromiseOrValue<string>,
      _tokenIDStart: PromiseOrValue<BigNumberish>,
      _tokenIDEnd: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    massRegistrerERC1155Default(
      _GBM: PromiseOrValue<string>,
      _initiator: PromiseOrValue<string>,
      _ERC1155Contract: PromiseOrValue<string>,
      _tokenID: PromiseOrValue<BigNumberish>,
      _indexStart: PromiseOrValue<BigNumberish>,
      _indexEnd: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    massRegistrerERC1155Each(
      _GBM: PromiseOrValue<string>,
      _initiator: PromiseOrValue<string>,
      _ERC1155Contract: PromiseOrValue<string>,
      _tokenID: PromiseOrValue<BigNumberish>,
      _indexStart: PromiseOrValue<BigNumberish>,
      _indexEnd: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    massRegistrerERC721Default(
      _GBM: PromiseOrValue<string>,
      _initiator: PromiseOrValue<string>,
      _ERC721Contract: PromiseOrValue<string>,
      _tokenIDStart: PromiseOrValue<BigNumberish>,
      _tokenIDEnd: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    massRegistrerERC721Each(
      _GBM: PromiseOrValue<string>,
      _initiator: PromiseOrValue<string>,
      _ERC721Contract: PromiseOrValue<string>,
      _tokenIDStart: PromiseOrValue<BigNumberish>,
      _tokenIDEnd: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    massRegistrerERC1155Default(
      _GBM: PromiseOrValue<string>,
      _initiator: PromiseOrValue<string>,
      _ERC1155Contract: PromiseOrValue<string>,
      _tokenID: PromiseOrValue<BigNumberish>,
      _indexStart: PromiseOrValue<BigNumberish>,
      _indexEnd: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    massRegistrerERC1155Each(
      _GBM: PromiseOrValue<string>,
      _initiator: PromiseOrValue<string>,
      _ERC1155Contract: PromiseOrValue<string>,
      _tokenID: PromiseOrValue<BigNumberish>,
      _indexStart: PromiseOrValue<BigNumberish>,
      _indexEnd: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    massRegistrerERC721Default(
      _GBM: PromiseOrValue<string>,
      _initiator: PromiseOrValue<string>,
      _ERC721Contract: PromiseOrValue<string>,
      _tokenIDStart: PromiseOrValue<BigNumberish>,
      _tokenIDEnd: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    massRegistrerERC721Each(
      _GBM: PromiseOrValue<string>,
      _initiator: PromiseOrValue<string>,
      _ERC721Contract: PromiseOrValue<string>,
      _tokenIDStart: PromiseOrValue<BigNumberish>,
      _tokenIDEnd: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
